services:
  streamlit:
    build: .
    container_name: streamlit_app
    expose:
      - "8501"
    volumes:
      - ./recordings:/app/recordings

  caddy:
    image: caddy:2
    container_name: caddy_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

